nodeLinker: node-modules

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "${GITHUB_PACKAGES_TOKEN}"
    npmScopes:
      mutinex: true

npmPublishRegistry: "https://npm.pkg.github.com"