nodeLinker: node-modules

npmScopes:
  Mutinex:
    npmRegistryServer: https://npm.pkg.github.com
    npmPublishRegistry: https://npm.pkg.github.com
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_PACKAGES_TOKEN}