name: Cloud Infra - Test, Build & Publish

on:
  push:
    branches:
      - main
  pull_request:
  #   paths-ignore:
  #     - '.github/workflows/**'

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mutinex'

      - run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run tests
        run: yarn test
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build package
        run: yarn build
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish:
    name: Publish to GitHub Packages
    needs: test-and-build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if package.json changed
        id: check-package
        run: |
          if git diff HEAD^ HEAD --name-only | grep -q "^lib/cloud-infra/package.json$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v4
        if: steps.check-package.outputs.changed == 'true'
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mutinex'

      - run: corepack enable
        if: steps.check-package.outputs.changed == 'true'

      - name: Install dependencies
        if: steps.check-package.outputs.changed == 'true'
        run: yarn --frozen-lockfile
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build package
        if: steps.check-package.outputs.changed == 'true'
        run: yarn build
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to GitHub Packages
        if: steps.check-package.outputs.changed == 'true'
        run: yarn npm publish
        env:
          GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
